# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('info', models.CharField(blank=True, max_length=1023)),
                ('mode', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hStart', models.IntegerField()),
                ('mStart', models.IntegerField()),
                ('hEnd', models.IntegerField()),
                ('mEnd', models.IntegerField()),
            ],
        ),
    ]
