# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SscData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('info', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('imgUrl', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['id']},
        ),
    ]
