# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SscData', '0002_auto_20170815_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('imgUrl', models.CharField(max_length=255)),
                ('webUrl', models.CharField(blank=True, max_length=255)),
                ('mode', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
